# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Angular CLI
      run: |
        rm -rf node_modules
        npm install -g @angular/cli

    - name: Install @ng-bootstrap/ng-bootstrap
      run: npm install --legacy-peer-deps

    - name: Build
      run: |
        ng build --prod
        dir

    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
          server: mohammedaggoun.com  # Remove the "ftp://" prefix
          username: ${{ secrets.FTP_USER }}  # Your GitHub secret for FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # Your GitHub secret for FTP password
          local-dir: ./dist/  # The directory with your built Angular project
          server-dir: /public_html/v1/  # The target directory on your Hostinger server
    

